const dummyEvent = [
	{
		pictures: {
			eventPicture: 'https://www.meetandeat-berlin.de/img/logo.svg',
			coverPicture: '',
		},
		adress: {
			street: '',
			city: '',
		},
		private: false,
		categories: [],
		_id: '62b185e11a4caaa125207cab1',
		eventName: 'Event1',
		eventPicture: '',
		coverPicture: '',
		participates: [],
		desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam',
		date: 'THU 30. Jun',
		location: [],
	},
	{
		pictures: {
			eventPicture: 'https://www.meetandeat-berlin.de/img/logo.svg',
			coverPicture: '',
		},
		adress: {
			street: '',
			city: '',
		},
		private: false,
		categories: [],
		_id: '62b185e11a4caaa125207cab2',
		eventName: 'Event 2',
		eventPicture: '',
		coverPicture: '',
		participates: [],
		desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam',
		date: 'THU 30. Jun',
		location: [],
	},
	{
		pictures: {
			eventPicture: 'https://www.meetandeat-berlin.de/img/logo.svg',
			coverPicture: '',
		},
		adress: {
			street: '',
			city: '',
		},
		private: false,
		categories: [],
		_id: '62b185e11a4caaa125207cab3',
		eventName: 'Event 3',
		eventPicture: '',
		coverPicture: '',
		participates: [],
		desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam',
		date: 'THU 30. Jun',
		location: [],
	},
	{
		pictures: {
			eventPicture: 'https://www.meetandeat-berlin.de/img/logo.svg',
			coverPicture: '',
		},
		adress: {
			street: '',
			city: '',
		},
		private: false,
		categories: [],
		_id: '62b185e11a4caaa125207cab4',
		eventName: 'Event4',
		eventPicture: '',
		coverPicture: '',
		participates: [],
		desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam',
		date: 'THU 30. Jun',
		location: [],
	},
	{
		pictures: {
			eventPicture: 'https://www.meetandeat-berlin.de/img/logo.svg',
			coverPicture: '',
		},
		adress: {
			street: '',
			city: '',
		},
		private: false,
		categories: [],
		_id: '62b185e11a4caaa125207cab5',
		eventName: 'Event 5',
		eventPicture: '',
		coverPicture: '',
		participates: [],
		desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam',
		date: 'THU 30. Jun',
		location: [],
	},
];

export default dummyEvent;
